### ISSUE TITLE
Unable to Connect to SSL port

### ISSUE THREAD

**Issue by mogalt** [maciejmiklas/cyclop#131]
Trying to connect to Cassandra host's SSL port. Unable to connect with the following error 
Unexpected error during transport initialization (com.datastax.driver.core.ConnectionException:

Contents of ../cyclop-master/cyclop-webapp/src/main/resources/cyclop.properties:
cassandra.useSsl: true
cassandra.truststore.path:/path/to/folder/cassandra.truststore.dev.jks
cassandra.truststore.password:blahblah

Is this the right set of properties? Can someone please advise? Thanks.

**Comment by maciejmiklas** [comment]
You should put into cyclop.properties only cassandra.useSsl. Path to truststore has to be a JDK property like: -Djavax.net.ssl.trustStorePassword=....

**Comment by mogalt** [comment]
Thanks that worked. 

For anyone interested, I added jetty plugin in pom and using the following command to run. 

mvn jetty:run -Djavax.net.ssl.trustStore=/path/to/trustore/cassandara.truststore.jks 
-Djavax.net.ssl.trustStorePassword=blahblah
